CREATE TABLE IF NOT EXISTS  Chord (chordId PRIMARY KEY VARCHAR(50)NOT NULL, chordName VARCHAR(25) NOT NULL);
CREATE TABLE IF NOT EXISTS  User (userId PRIMARY KEY VARCHAR(50)NOT NULL, userName VARCHAR(25) NOT NULL, password VARCHAR(25) NOT NULL);
CREATE TABLE IF NOT EXISTS  ChordVariation (variationId PRIMARY KEY VARCHAR(50)NOT NULL, chordId FOREIGN KEY (chordId) REFERENCES Chord(chordId), 
USER_ID FOREIGN KEY (USER_ID) REFERENCES User(userId), variationName VARCHAR(25) NOT NULL), startingFret INTEGER NOT NULL, ;